### ISSUE TITLE
DOI Tweaks for JOSS submission

### ISSUE THREAD

**Issue by AJQuinn** [fairdataihub/SODA-for-SPARC#273]
Hello JOSS editor here - thanks for fixing up the DOIs, there is one final tweak needed on this line:

https://github.com/fairdataihub/SODA-for-SPARC/blob/f51ab22d0174b0e0c3b65b0af00864be78b6b3b1/paper/paper.bib#L75C40-L75C41

Need to drop the close parenthesis at the end of the DOI.
```
  doi = {10.12688/f1000research.75071.1)}
```

Our paper compiling tests should pass once that is through

https://github.com/openjournals/joss-reviews/issues/5952

**Comment by megasanjay** [comment]
@bvhpatel

**Comment by bvhpatel** [comment]
Addressed that a few days ago but forgot to close the issue: https://github.com/fairdataihub/SODA-for-SPARC/commit/52e7b8c520d90fdf71bb1ec5e59944fdcbbb0946. Thanks!
