### ISSUE TITLE
[JOSS Review] Update the documentation portal link in README

### ISSUE THREAD

**Issue by abhishektiwari** [fairdataihub/SODA-for-SPARC#299]
Update link [our dedicated webpage](https://fairdataihub.org/sodaforsparc) under [documentation](https://docs.sodaforsparc.io) section of README.

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/6140)

**Comment by aaronm-2112** [comment]
Closing the issue as it has been addressed as per 2094938

Thanks for the feedback!
